### ISSUE TITLE
Find out what atom-eval is

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/JunoDocs.jl#1]
Right now it's listed as "Super secret stuff".

**Comment by pfitzseb** [comment]
It isn't necessary for Juno, so I've removed it from the docs. IIUC it does for Atom (or coffeescript) what Juno does for Julia.

**Comment by MikeInnes** [comment]
Yup. The main reason it's not documented is that it has a lot more trip-ups than Julia eval. But it's pretty sweet if you know what you're doing, and I'm happy to help anyone interested get set up.
