### ISSUE TITLE
Document what branch to edit when contributing

### ISSUE THREAD

**Issue by waldyrious** [JunoLab/JunoDocs.jl#12]
I came here to propose a change from `Ctrl+,` to `Ctrl`+`,` or `Ctrl + ,` in installation.md, because the comma is easy to miss next to the plus sign, but I wasn't able to figure out what branch one is supposed to edit from the instructions in the README. [Both master and gh-pages](https://github.com/JunoLab/JunoDocs.jl/branches) seem to have been edited recently, so it isn't clear which one should be edited.

In any case, it's always nicer to be explicit :)

**Comment by pfitzseb** [comment]
Should be better now :)

**Comment by waldyrious** [comment]
Thanks for the quick reaction! For reference, the relevant commit is 278e93c.

**Comment by waldyrious** [comment]
Out of curiosity, what is the `gh-pages` branch for? Is it populated by Documenter.jl?

**Comment by pfitzseb** [comment]
Exactly. Have a look at [this](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html) if you wanna know more about it.

**Comment by waldyrious** [comment]
Thanks :)
