### ISSUE TITLE
Add link in the repo description and the README

### ISSUE THREAD

**Issue by waldyrious** [JunoLab/JunoDocs.jl#13]
For convenience, it would be nice if the repo description (which has a field for a URL) and the README contained a link to the actual docs --> http://docs.junolab.org

**Comment by pfitzseb** [comment]
The readme does contain a link to the docs in the form of the `docs|latest` badge, but having the link in the repo description makes sense to me. Don't have the rights to do that though, maybe @ChrisRackauckas can?

**Comment by ChrisRackauckas** [comment]
I added one in both places. Most people shouldn't really be coming to the repo for the docs, but if they do, this will help them get back on track.
