### ISSUE TITLE
How to actually use Juno with remote Julia session? Is REPL supported? If not, what is supported?

### ISSUE THREAD

**Issue by adamryczkowski** [JunoLab/JunoDocs.jl#28]
I have followed the http://docs.junolab.org/latest/man/faq.html#Connecting-to-an-external-julia-session-on-a-remote-machine-1 and got the confirmation (on both Atom and system notificator), that I have successfully connected with the remote Julia session.

Yet when I try to start REPL I get an atom warning "`Can't boot Julia with a Julia client running.` `Stop the current client with Packages → Julia → Stop Julia.`". When I do this and open Julia again, I get the *local* Julia session in the REPL pane.

If it is not a bug but a feature, please update the manual (or I can do this, once you explain it) with the information about what functionality is supported when working on the remote Julia session, and how to use it.

**Comment by adamryczkowski** [comment]
It seems that the evaluation of expressions in the document (the one that gets triggered by Ctr+Enter) works remotely. Too bad, that there is no REPL - but fortunately I can still use the remote server console, so it is just an inconvenience, not a real show-stopper. 

I still hope for a remote REPL support, so I'll keep this thread open until I get a response.

**Comment by pfitzseb** [comment]
Yeah, I've been meaning to look into this. We'll definitely have something better in the (hopefully near) future.

Btw, if you open the ssh session inside of Juno (`Julia Client: New Terminal` just gives you a terminal which you can use for that) there's not *that* much of a difference to using the build-in Julia REPL.

**Comment by pfitzseb** [comment]
I've updated the docs, should be much clearer now.
