### ISSUE TITLE
Shortcut documentation for Shift+Enter

### ISSUE THREAD

**Issue by dkaschek** [JunoLab/JunoDocs.jl#46]
By chance, I found that Shift+Enter was a shortcut that let me execute a line or a code block and **move the curser to the next line/block**. I was looking for this short-cut long ago and could not find it in the Juno documentation. Would you mind putting it there? Are there other "hidden" shortcuts?

**Comment by pfitzseb** [comment]
There probably are other keybindings you're not aware of, yes -- our keybindings aren't very well documented. Luckily, Atom can provide you with a fairly complete list: Go to `Settings` > `Keybindings` and type `julia` into the search box:
![image](https://user-images.githubusercontent.com/6735977/68487780-026dbf80-0244-11ea-9917-513fded9e7a3.png)

We might be able to automatically generate a list like that and include it in the docs though.

**Comment by dkaschek** [comment]
Thank you for the quick reply. For myself, coming from RStudio, the shortcut ctrl-j ctrl-f, formatting the code, is another interesting one.
